/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ATM;


import ATM.view.AtmWindow;
import javafx.application.Application;
import javafx.stage.Stage;


import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.net.URISyntaxException;
import java.net.URL;


/**
 * Example javadoc test summary sentence...
 */

public class App extends Application {

    @Override
    public void start(Stage primaryStage) throws IOException, URISyntaxException {

//        Handler
        AtmWindow window = new AtmWindow(primaryStage);
        window.run();
//
    }

    public static void main(String[] args) {
        launch(args);
    }


}
